media: fix chrome setCodecPreferences
We were getting the preferred codecs from RTCRtpSender, but Chrome on Mac
supports sending a higher version of H264 than it can receive. See here:

https://groups.google.com/g/discuss-webrtc/c/QS7y-7zR5ok

This was causing chrome to fail to set our preferred codecs with an
error like:

InvalidModificationError: Failed to execute 'setCodecPreferences' on
'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name
"H264".

So instead we get the capabilities from RTCRtpReceiver, sort
them for our preferred codecs when the relative flags areenabled
(instead of adding newcodecs), then set them on the transceiver.
This allows us to enable both AV1 and VP9 flags simultaneously, where
before an early VP9 entry would break the loop, leaving AV1 stuck near
the bottom of the codec list.